services:
  # 1. Database
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - pgdata_inventory:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Load Script Magic tadi
    ports:
      - "${APP_DB_PORT}:5432" # Pakai 5435 biar gak bentrok sama project sebelumnya
    restart: unless-stopped

  # 2. Backend (API)
  api:
    image: jawaracode/jawara-api:latest
    ports:
      - "${APP_API_PORT}:5000"
    environment:
      PORT: 5000
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
    depends_on:
      - db
    restart: unless-stopped

  # 3. Frontend (React)
  web:
    image: jawaracode/jawara-web:latest
    ports:
      - "${APP_WEB_PORT}:5173"
    environment:
      VITE_API_BASE_URL: "http://localhost:${APP_API_PORT}"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pgdata_inventory: