name: Unit Testing (Build Check)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Create Dummy .env
      run: |
        echo "APP_WEB_PORT=5173" >> .env
        echo "APP_API_PORT=5000" >> .env
        echo "APP_DB_PORT=5435" >> .env
        echo "DB_USER=test_user" >> .env
        echo "DB_PASS=test_pass" >> .env
        echo "DB_NAME=test_db" >> .env
        echo "NODE_ENV=test" >> .env
    
    - name: Build Docker Images
      run: docker compose build